general {
    hide_cursor = true
    ignore_empty_input = true
    fractional_scaling = false
}

background {
    path = /home/$USER/Pictures/wallpapers/others/forest_road.jpg

    blur_passes = 2
    contrast = 1
}

animations {
    animation = fadeIn, 0
    animation = fadeOut, 0
    animation = inputFieldColors, 0
}

# User box
shape {
    size = 300, 50

    rounding = 0
    border_size = 2

    color = rgba(102, 92, 84, 0.33)
    border_color = rgba(168, 153, 132, 0.95)

    position = 0, 270
    halign = center
    valign = bottom
}

# Time
label {
    text = $TIME

    font_size = 115
    font_family = Maple Mono Bold

    shadow_passes = 3

    color = rgba(235, 219, 178, 0.9)

    position = 0, -150
    halign = center
    valign = top
}

# Date
label {
    text = cmd[update:1000] echo "- $(date +'%A, %B %d') -"

    font_size = 18
    font_family = Maple Mono

    shadow_passes = 3

    color = rgba(235, 219, 178, 0.9)

    position = 0, -350
    halign = center
    valign = top
}

# Username
label {
    text = $USER

    font_size = 15
    font_family = Maple Mono Bold

    color = rgba(235, 219, 178, 1)

    position = 0, 284
    halign = center
    valign = bottom
}

input-field {
    size = 300, 50

    rounding = 0
    outline_thickness = 2

    dots_spacing = 0.4

    font_family = Maple Mono Bold
    font_color = rgba(235, 219, 178, 0.9)

    outer_color = rgba(168, 153, 132, 0.95)
    inner_color = rgba(102, 92, 84, 0.33)

    check_color = rgba(152, 151, 26, 0.95)
    fail_color = rgba(204, 36, 29, 0.95)

    capslock_color = rgba(215, 153, 33, 0.95)
    bothlock_color = rgba(215, 153, 33, 0.95)

    fade_on_empty = false

    placeholder_text = <i><span foreground="##fbf1c7">Enter Password</span></i>

    position = 0, 200
    halign = center
    valign = bottom
}
