general {
    hide_cursor = true
    ignore_empty_input = true
    fractional_scaling = false
}

animations {
    enabled = false
}

background {
    path = screenshot
    blur_passes = 4
    blur_size = 4
    contrast = 1.25
}

label {
    text = $TIME
    font_size = 36
    font_family = Maple Mono

    color = rgb(fbf1c7)

    position = 0, 0
    halign = center
    valign = center
}

input-field {
    size = 225, 225
    outline_thickness = 9

    hide_input = true
    fade_on_empty = false

    fail_text = 
    placeholder_text = 

    font_color = rgb(FBF1C7)

    inner_color = rgba(3C3836DD)
    outer_color = rgb(689D6A)

    hide_input_base_color = rgb(FABD2F)

    check_color = rgb(B8BB26)
    fail_color = rgb(CC241D)

    capslock_color = rgb(d65d0e)

    position = 0, 0
    halign = center
    valign = center
}
